"""empty message

Revision ID: 34b37acfa162
Revises: 
Create Date: 2021-09-10 14:04:45.797545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b37acfa162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=100), nullable=False),
    sa.Column('penulis', sa.String(length=100), nullable=False),
    sa.Column('penerbit', sa.String(length=100), nullable=False),
    sa.Column('tahun', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penjualan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('hari', sa.String(length=20), nullable=True),
    sa.Column('buku_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buku_id'], ['buku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penjualan')
    op.drop_table('buku')
    # ### end Alembic commands ###
